# Generated by Django 5.1.5 on 2025-01-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('especialidade', models.CharField(max_length=200)),
                ('clinica_nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agenda', models.JSONField(default=list)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
